# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Trekerz # your blog title name
subtitle:  
author: Trekerz # 作者
language: 
timezone: 

# custom Site settings
# more detail check out docs
SEOTitle: Trekerz's blog 
header-img: http://prjadt00w.bkt.clouddn.com/default-img.jpg
email: zjf007@qq.com
description: "庄嘉峰在 Github 上的个人博客"
keyword: 'trekerz blog github'

favicon: /favicon.png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://trekerz.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# SNS settings
# RSS:
weibo_username: zjfjz
zhihu_username: trekerz
github_username: trekerz
twitter_username: GarfunkelZhuang
facebook_username:  
linkedin_username:  

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: 

# Duoshuo settings
duoshuo_username:  # 你的多说帐号
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Use livere
use_livere:

# Analytics settings
# Baidu Analytics
ba_track_id: e3e6f83e945518142f014116fc5aacc7
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar-about-description: "求知若饥 虚心若愚"
sidebar-avatar: http://prjadt00w.bkt.clouddn.com/avator.jpg


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# friends
friends: [
    {
        title: "掘金",
        href: "https://juejin.im"
    },
    {
        title: "开源中国",
        href: "https://www.oschina.net/project/lang/28/javascript"
    },
    {
        title: "简书",
        href: "http://www.jianshu.com/"
    }
]

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:trekerz/trekerz.github.io.git
  branch: master


# img CDN path
cdn-url:  https://h1.ioliu.cn

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: ""
clip-avatar: ""
clip-home-post-bg: ""

# post default images
post-default-img: default-img.jpg
post-default-img-mobile: default-img.jpg

# search api , set your custom key
swiftype_key: 


# archive page title 
archive:
    title: ARCHIVE
    description: 可以根据归档日期检索所有文件
